name: Space Check

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  check_spaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Run space check script
        run: bash check_spaces.sh
